import { createApp } from 'vue'
import App from './App.vue'
import { Amplify } from 'aws-amplify';
// Import your Amplify configuration file
import amplifyconfig from '../amplifyconfiguration.json'; // Or aws-exports.js if generated by Amplify CLI

// Configure Amplify
Amplify.configure(amplifyconfig);

const app = createApp(App)

app.mount('#app')
